### ISSUE TITLE
Hitting Back from the Main Menu terminates the app instead of leaving it running in the background

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#10]
![image](https://user-images.githubusercontent.com/47233113/54873324-37023900-4d91-11e9-9aa1-3bb82a3b149b.png)

We notice if you are running the app and hit the back arrow from the app’s main menu and return to the app dock the app is app remains as a running app but if you select the app from the running list or from its icon the app restarts (you see the landing page again).

**OCV:** This is the intended functionality for Android applications. To dismiss an app completely, open the applications menu (tap the menu/box icon below the screen or at the bottom of the screen, depending on the device; on certain distributions of Android 9, swiping up from the bottom of the screen) and swipe the application away (upwards).

**RCMP:** I think there is a disconnect.  From the RCMP app’s main menu if you press the back button you return to the phone’s main screen but with the app still running in the background if you select the RCMP app (from the list of running apps or from the app’s icon) the app restarts instead of the desired behaviour of resuming.  See the following video for more information:
https://1drv.ms/v/s!Au0wmqpYyP_CiPJoA02vC0XK4gCNUg

**Comment by jcarterOCV** [comment]
We understand what you are referencing here but it is working as intended by design.
We reload the menu when backing out, as we are reloading the menu layout on fresh open to the main menu (in case the menu or a feed has changed during the time you had it closed).

**Comment by rcmp-randallw** [comment]
Understood, thanks for the clarification.
