### ISSUE TITLE
Delay/Lag accessing Developer Feedback

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#11]
![image](https://user-images.githubusercontent.com/47233113/54873333-5f8a3300-4d91-11e9-8565-b6280eb36952.png)
When the app first starts if you go to Settings|Developer Feedback nothing happens.  It can take 4+ taps before the Developer Feedback page appears.

**RCMP:** Latest version (1.5.5. build 16) still lags.  You need to tap the option 2 – 4 times sometimes.  Once it is displayed it appears fairly consistently.

**Comment by cwaldonOCV** [comment]
I believe the problem to be related to how we're dealing with the "Developer Settings" hidden shortcut. For now we'll move it to the top right of the toolbar, as an invisible icon. This will be visible in the next version.
