### ISSUE TITLE
Remove duplicate word History underneath Alert History when accessed from footer

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#12]
When you press “Committed to Safe Homes, Safe Communities” can you remove the small History underneath the title Alert History, so it appears the same as if you press Alert History from the main menu:
![image](https://user-images.githubusercontent.com/47233113/54873349-b2fc8100-4d91-11e9-91b7-39472e70967b.png)

**Comment by cwaldonOCV** [comment]
This will be fixed in the next version.
