### ISSUE TITLE
Location and weather do not update on app resume

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#13]
If I change locations with the app running in the background and set focus to the mobile app, or sometimes if I just wake up the phone and resume the app it appears to be loading the weather, but it never completes updating unless I go to a Page and then return to the main menu, or restart the app:
![image](https://user-images.githubusercontent.com/47233113/54873364-ee974b00-4d91-11e9-9b22-81eedffa7ab3.png)

**Comment by jcarterOCV** [comment]
Sometimes the gps and/or api service delays and times out the request.  When it comes back to the menu, it reloads and this issue typically does not happen twice.
This would be a hard one to track down and resolve, if you want us to put extra time into this we can.

**Comment by rcmp-randallw** [comment]
What is the refresh interval for the weather widget? 

On timeout can we just have a a message appear 'No Connection - Tap to Retry' that if the user taps the same behaviour of returning to the main menu is invoked?.  

The spinning wheel implies that something is happening and if you wait sufficient time it will finish but that's not the case.

**Comment by rcmp-randallw** [comment]
Like in issue #4 we want when the app has focus (e.g. applicationDidBecomeActive or OnResume) to refresh the location and the temperature.  Going out of the app and coming back into is not triggering a refresh.

The use case is someone resuming the app, noting the weather and location and then calling the police from the Contacts section with out of date information or a member running the app to log the weather in his/her notebook at a particular time and if they don't exit and return to the main menu the information is incorrect.

**Comment by cwaldonOCV** [comment]
In the latest build, it should be updating whenever it is redrawn to the screen, as in any time it comes from a feature, on resuming the app, on waking the phone, etc. This is not unique to the weather feature, and should also be present in the ticker tape. We can display a message on failure, and have a prompt to reload it. If this is what's desired, you can expect it in the next build.

**Comment by rcmp-randallw** [comment]
I started the app in Richmond, pressed the home button, drove 6 minutes and then resumed the app (hit the app icon from the main menu to resume the app):
![Screenshot_20190409-201920_Richmond RCMP](https://user-images.githubusercontent.com/47233113/55852733-fd605a80-5b12-11e9-88f9-0a1e08bb05ef.jpg)
and the location was still showing Richmond, but if I press "Where Am I?" it correctly shows Vancouver:
![Screenshot_20190409-201926_Richmond RCMP](https://user-images.githubusercontent.com/47233113/55852734-fdf8f100-5b12-11e9-97e2-b6c561b6a817.jpg)
Is there a time duration where a resume (app gets focus after being on the home screen and the app's icon is pressed or selecting the app from the running app list), where the screen isn't supposed to refresh?  Anytime the app gets focus from the main menu or another app we would like to see a refresh.

On the return trip I did the same thing but on a resume the wait wheel was displayed and everything was updated.

**Comment by rcmp-randallw** [comment]
In build 1.5.6 (17) if the app is in the background and is resumed the location is not updated (I am in Squamish but it is showing Lions Bay):

![Screenshot_20190414-144333_Richmond RCMP](https://user-images.githubusercontent.com/47233113/56107111-4ccece00-5ef9-11e9-8d72-8aedaa3fc6e2.jpg)
![Screenshot_20190414-144350_Richmond RCMP](https://user-images.githubusercontent.com/47233113/56107121-56f0cc80-5ef9-11e9-8186-7046c378ed28.jpg)
if I press the Home but and resume the app the location will update:
![Screenshot_20190414-144422_Richmond RCMP](https://user-images.githubusercontent.com/47233113/56107130-5eb07100-5ef9-11e9-82da-4e895d653afd.jpg)
but if i restart the app the location shows Richmond (despite the widget being set to 'Local'):
![Screenshot_20190414-144433_Richmond RCMP](https://user-images.githubusercontent.com/47233113/56107152-856ea780-5ef9-11e9-8938-480b929a9a06.jpg)

**Comment by rcmp-randallw** [comment]
In build 1.5.6 (17) if the app is left in the foreground and then the screen times out (and the device automatically locks) after an extended duration (e.g. greater than 15 minutes) when you log back into the device the weather/location widget does not update:
![Screenshot_20190414-182455_Richmond RCMP](https://user-images.githubusercontent.com/47233113/56107202-da122280-5ef9-11e9-8ba3-dfc01d6c4b38.jpg)
and going into a menu item and returning to the main menu nor pressing the home button and then resuming the app does not correct this condition.

**Comment by rcmp-randallw** [comment]
Using build 17 if I close the app and restart, close the app and restart repeatedly while in Vancouver it is hit and miss if the app displays Richmond or Vancouver. It seems as though if the startup is quick the location will update but if there is any sort of pause (perhaps loading the menus) the location does not update.

**Comment by jcarterOCV** [comment]
This will get resolved in 1.5.7 (18) that we are working on.

**Comment by rcmp-randallw** [comment]
Using 1.5.7 (18) if I run the app and then press Home and then drive to another town and resume the app either the old location/weather will appear:

![Screenshot_20190525-180431_Richmond RCMP](https://user-images.githubusercontent.com/47233113/58397065-36da2000-8004-11e9-8a21-e29094fdf337.jpg)

until you click on the weather/location widget and return to the main menu:

![Screenshot_20190525-180437_Richmond RCMP](https://user-images.githubusercontent.com/47233113/58397066-36da2000-8004-11e9-81a8-d52424b55863.jpg)
![Screenshot_20190525-180504_Richmond RCMP](https://user-images.githubusercontent.com/47233113/58397067-3772b680-8004-11e9-81da-59eff4c1379c.jpg)

it will update.

Sometimes when you do the same behavior (run the app, press Home, drive to a new location and resume the app) the Location/Weather will not load:

![Screenshot_20190526-220759_Richmond RCMP](https://user-images.githubusercontent.com/47233113/58397122-756fda80-8004-11e9-8320-5046d437cb5c.jpg)

If I close the app and restart or access a menu item and return to the main menu

**Comment by rcmp-randallw** [comment]
With build 19 the main menu refreshes (reloads location, weather and moves back to the main menu) every time the app resumes regardless of where the user exited the app (switched to another app or hit the home button).  Further the app stops if you attempt to access Alerts.

**Comment by rcmp-randallw** [comment]
With build 20 if the app is running and you lock the phone and then change locations and unlock the phone to resume the app, or you run the app and then press home and then change locations and resume the app the following appears and it never stops:
![Screenshot_20190615-101344_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557661-22020400-8f94-11e9-9d1d-f6dce264805c.jpg)

And then if you terminate the app and restart it is showing "Richmond" despite being in the Langley area:
![Screenshot_20190615-121835_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557669-6e4d4400-8f94-11e9-8058-09bb215959f2.jpg)
![Screenshot_20190615-121842_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557670-6e4d4400-8f94-11e9-9629-d28096e643b9.jpg)
and then if you select a menu item (blog or page) and then resume the location is correct (although sometimes when it loads it looks like it loads 3 times (you see the spinning wheel and then temperature three times):
![Screenshot_20190615-121921_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557677-b8362a00-8f94-11e9-9c6d-c6c7a366db00.jpg)
If I stop and restart the app sometimes the location stays as Richmond, despite being in a different City (e.g. Langley):
![Screenshot_20190615-122334_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557682-da2fac80-8f94-11e9-97f0-bb06f7bf2fae.jpg)
it appears the temperature/locationon the weather widget is based on "Richmond" and the Location and Weather Pages are based on the setting value resulting in the discrepancy between the two values?

**Comment by rcmp-randallw** [comment]
Here is a video that describes how to reproduce the issue:

Step 1. Run the app and then put in the background:
https://1drv.ms/v/s!Au0wmqpYyP_CiaVCLcqQw6B4j8V-oA

Step 2. Change Location and then unlock the device and resume the app:
https://1drv.ms/v/s!Au0wmqpYyP_CiaVDcEi-2gjMPmOihQ

**Comment by rcmp-randallw** [comment]
With Version 1.5.9 (20) released on 24 JUL 2019, 13:56 the temperature updates on startup and resume.  Can we just force a location refresh in the same manner if/when location sharing is turned on (regardless of location change event) in a similar manner to resolve this issue?

**Comment by rcmp-randallw** [comment]
With Version 1.5.11 (22) released on 19 Aug 2019 location updates on startup and resume. 

One cosmetic issue we have noticed is on startup (after a forced close) the main menu displays "Richmond, BC" briefly and then changes to the current location (e.g.  Vancouver, BC) when in Vancouver, BC.  Like the iOS version can the location on startup be set to blank, and then be set to the current location, and if the current location cannot be found (e.g. Location Services is off) then default to Richmond, BC?

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
We do not have the ability to change that, as the reason is when the app opens it tries to instantly grab the user's location and does not have time to get it before it loads.  This in turn returns an error and shows the default location.

**Comment by rcmp-randallw** [comment]
Understood and acceptable.
