### ISSUE TITLE
Pressing the image of an Alert should display the alert

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#15]
When viewing the Alert History (just like with Blog Listings):
![image](https://user-images.githubusercontent.com/47233113/54873438-703ba880-4d93-11e9-8963-e9a0259bcc30.png)
if the user presses the image the Alert should load, currently nothing happens, the user must press the alert title or body to display the alert.

**Comment by cwaldonOCV** [comment]
This will be fixed in the next version.
