### ISSUE TITLE
Change text on About Richmond RCMP page

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#16]
On this page please change instances of "Richmond RCMP App" to "Richmond RCMP Mobile App":
![Screenshot_20190323-055833_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54873463-01128400-4d94-11e9-8760-8fa7bbccbb0c.jpg)

**Comment by cwaldonOCV** [comment]
This was updated yesterday, and the changes should be reflected in the app.
