### ISSUE TITLE
There seems to be a slight disconnect between the temperature from the weather page and the banner

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#17]
The temperature from the banner (Current: 7, Low: 6, High: 13):
![Screenshot_20190323-062900_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54873489-6b2b2900-4d94-11e9-9f68-5e8eae02f0e7.jpg)
Is different from Richmond (Current: 8, Low: 6, High: 13):
![Screenshot_20190323-062923_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54873490-6b2b2900-4d94-11e9-9fe0-ef90c93a5f22.jpg)
And local (which was still Richmond) (Current: 8, Low: 6, High: 14):
![Screenshot_20190323-063213_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54873491-6b2b2900-4d94-11e9-9d27-1ff117e26b73.jpg)

**Comment by jcarterOCV** [comment]
This looks to be like the Richmond you have on your main menu in the first image was referencing your current location, but when opening you are looking at the static feed.
The distance from that lat long to yours could make a difference like that.
If you will verify, set your widget to "Built-in Location" and verify the widget and the weather feature are correct for "Richmond".

Something else that could call that is if you sat on the main menu for a few minutes and the forecast changed when you come into the feature, it will show the most recent forecast.  Backing out to the menu after that would update the menu to match in that case.

**Comment by rcmp-randallw** [comment]
Even if I close and restart the application the current, high and low in the weather widget typically does not match the current, high and low of the weather feature for Richmond or Local (when I am in Richmond).  

We would like the weather widget to display the current weather set by the Weather Widget setting and if set to Richmond the weather widget's weather, current, high and low should match the weather feature on the Richmond tab.  Conversely, if set to Local the weather widget's weather, current, high and low should match the weather feature on the Local tab.

**Comment by cwaldonOCV** [comment]
I'll take a look at this, but I believe we're using the same information for both API calls on the backend. If this is not the case, it will be fixed in the next version.

**Comment by rcmp-randallw** [comment]
This still appears to be an issue.  When the current Weather Widget setting is set to Local I would expect that the temperature in the widget and when viewing the weather (for Local) would be the same (e.g. same source and longitude/latitude) but the high and low in the widget always appears 1 degree off from the weather page:

![Screenshot_20190409-192006_Richmond RCMP](https://user-images.githubusercontent.com/47233113/55852602-82973f80-5b12-11e9-9f82-81f471446763.jpg)
![Screenshot_20190409-192014_Richmond RCMP](https://user-images.githubusercontent.com/47233113/55852603-82973f80-5b12-11e9-94a1-d8c8b6dcb30f.jpg)

**Comment by rcmp-randallw** [comment]
The high and low consistently seem 1 degree lower on the widget vs. weather page but this only seems to happen when the unit of measurement is set to Canada (celsius).

**Comment by jcarterOCV** [comment]
This will get resolved in 1.5.7 (18) that we are working on.

**Comment by rcmp-randallw** [comment]
The temperature is not reloading when the app resumes but if you select weather from the widget and return to the main menu it reloads, at which point the weather on the widget and the weather page are in sync.

**Comment by rcmp-randallw** [comment]
There still seems to be a disconnect between the weather widget and the weather page but I think it is because on an app resume the weather widget is not updating.

If I resume the app the weather widget (low, current, high) states **15-16-20**:
![Screenshot_20190614-235325_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59548345-cdfb0f00-8f02-11e9-9063-43eaa43a8d98.jpg)
but the weather page states **15-15-20**:
![Screenshot_20190614-235329_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59548346-cdfb0f00-8f02-11e9-929f-f30ed8a8ae20.jpg)

If I terminate the app and restart the weather widget states **15-15-20**:
![Screenshot_20190614-235349_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59548347-cdfb0f00-8f02-11e9-97e1-ac139593d38b.jpg)
and the weather page also states **15-15-20**:
![Screenshot_20190614-235356_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59548348-cdfb0f00-8f02-11e9-9e53-966a68c7a220.jpg)

**Comment by rcmp-randallw** [comment]
It appears the temperature on the weather widget is based on "Richmond" and the Weather Page is based on the setting value resulting in the discrepancy between the two values?

![Screenshot_20190615-122409_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557625-08ac8800-8f93-11e9-8998-3476ff15b1b1.jpg)
![Screenshot_20190615-122415_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557626-09451e80-8f93-11e9-8266-b52ac0335da6.jpg)
![Screenshot_20190615-122420_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557627-09451e80-8f93-11e9-837f-40acaaeda10a.jpg)
![Screenshot_20190615-122428_Richmond RCMP](https://user-images.githubusercontent.com/47233113/59557628-09451e80-8f93-11e9-91fe-94630dada689.jpg)

**Comment by rcmp-randallw** [comment]
This issue is resolved with with the Version 1.5.9 (20) released on 24 JUL 2019, 13:56.
