### ISSUE TITLE
Settings|Weather Widget Location not being used to set weather location

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#18]
Despite the Weather Widget Location being set to 'Current Location':
![Screenshot_20190323-195700_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54874399-d0d4e080-4da7-11e9-8274-bd5106d62cf2.jpg)
The weather is always set to 'Richmond' during the current session and new sessions:
![Screenshot_20190323-195648_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54874398-d0d4e080-4da7-11e9-8e9a-dada5d44b242.jpg)
**Note: The setting persists between sessions it is just never used to set the weather in the Weather/Location banner.**

**Comment by jcarterOCV** [comment]
Are you referencing having the weather widget setting decide which tab to open to in the weather feature?

**Comment by rcmp-randallw** [comment]
Yes, the Setting should determine which tab to open in the weather feature and which location to display in the weather widget on the main menu.
