### ISSUE TITLE
Problem with Search bar cancel button and cursor not appearing

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#2]
(1) On an iPhone 5 running iOS 10.3.3 if you access any Blog listing (e.g. Calendar or Crime Prevention|Citizen Groups) and you click on the Search bar and then hit ‘Cancel’ if you click on the Search bar again the Cancel no longer appears:

![image](https://user-images.githubusercontent.com/47233113/54870602-0c4ebb00-4d66-11e9-8467-988cfedc0b5d.png)

(2) On an iPhone 5 running iOS 10.3.32 if you click on the Search bar under Contacts or a Blog Section (e.g. Calendar or Crime Prevention|Citizen Group) the flashing cursor indicating what control has focus appears does not appear:

![image](https://user-images.githubusercontent.com/47233113/54870602-0c4ebb00-4d66-11e9-8467-988cfedc0b5d.png)

**Comment by jcarterOCV** [comment]
Will be resolved with build 16

**Comment by rcmp-randallw** [comment]
This issue is resolved on an iPhone 5 running iOS 10.3.3 under Calendars but not under Blog listings (e.g. Crime Prevention|Block Watch):

![20190402_042118000_iOS](https://user-images.githubusercontent.com/47233113/55376462-5998fe00-54c5-11e9-8fb8-18e7e394144c.png)

**Comment by jcarterOCV** [comment]
Will be resolved with build 18
