### ISSUE TITLE
Search bar hangs or overcollapses

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#20]
When in a Blog listing if you pull down the blog entries slowly to reveal the search bar and delay the release the Search bar will stick descended:
![20190324_235640000_iOS](https://user-images.githubusercontent.com/47233113/54895805-95f1ac00-4e7e-11e9-9f57-b2c58cb4c90d.png)
or it will over-collapse:
![20190324_235852000_iOS](https://user-images.githubusercontent.com/47233113/54895806-968a4280-4e7e-11e9-8993-b8c9a662d993.png)

**Comment by jcarterOCV** [comment]
Should be resolved when build 17 comes out.
