### ISSUE TITLE
When the app first loads the location defaults to “Auburn, AL” can it just be blank?

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#21]
When the app first loads the location defaults to “Auburn, AL” briefly while the current location loads -- can it just be set blank on initialization while the current location loads?

**Comment by jcarterOCV** [comment]
This will get resolved with next build.

**Comment by rcmp-randallw** [comment]
Issued is confirmed resolved for iOS.

**Comment by cwaldonOCV** [comment]
This will be fixed in the next version.
