### ISSUE TITLE
If app starts without data connection it does not recover when connection restored

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#22]
If the mobile app is started in Airplane mode the user is correctly informed of the cached content and lack of Internet connection:
![Screenshot_20190324-232354_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54899411-fee02080-4e8c-11e9-9cff-bbf7d965e252.jpg)
but once the data connection is restored the app does not recover.  If you select an option (e.g. Where Am I? or a menu item) and return to the main menu the Weather/Location bar is restored and the popup menus are loaded but the banner graphic is not loaded: 
![Screenshot_20190324-232641_Richmond RCMP](https://user-images.githubusercontent.com/47233113/54899414-fee02080-4e8c-11e9-9304-b8008a6b7408.jpg)

**Comment by cwaldonOCV** [comment]
This will be fixed in the next version.
