### ISSUE TITLE
If app starts without data connection it does not recover when connection restored

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#23]
If the mobile app is started in Airplane mode the user is correctly informed of the cached content and lack of Internet connection:
![20190325_062539000_iOS](https://user-images.githubusercontent.com/47233113/54899691-e45a7700-4e8d-11e9-9e75-e6a05f67d640.png)
but once the data connection is restored the app does not recover until you select a menu item or select weather/Where Am I?

**Comment by jcarterOCV** [comment]
Added this in with build 16

**Comment by rcmp-randallw** [comment]
This is working for everything but the banner image.  I see the pinwheel spin and then disappear but the banner does not appear.  To re-create close the app, turn off data, run the app and you get the message "No Internet", then restore the data connection,
