### ISSUE TITLE
Pop-up menus sometimes contain additional blank entries

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#24]
Sometimes when selecting a popup menu from the main menu there are additional blank lines at the bottom of pop-up menu:

![16894B24-FF15-494D-81B6-E1236890D16D](https://user-images.githubusercontent.com/47233113/55004532-a21d5c80-4f97-11e9-9e91-6a084589e7f7.png)

**Comment by jcarterOCV** [comment]
Will be updated in build 16
