### ISSUE TITLE
In iOS 12.2.2 Popup menus are taking longer to load and "Loading" appears

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#27]
We noticed in the latest build (17) and/or iOS 12.2 there is a hesitation loading longer popup menus (e.g. Crime Prevention and Personal & Home Safety) and on an iPhone 7 or 8 the black box appears but it disappears before the word "Loading" appears so it just looks like a screen flash:

![20190404_041722000_iOS](https://user-images.githubusercontent.com/47233113/55529831-102ce800-5658-11e9-9b07-7f963f8d392e.png)
Is it possible to delay the appearance of "Loading" or remove it altogether if the delay of loading menus is not too long?

**Comment by ylin1CoR** [comment]
Would also like to point out that sometimes the sub-menu does not load at all (blank), and the user would need to close the sub-menu and click on the menu again.  See screenshot.  Will send video separately as I cannot attach them here.

iphone 7 ios 12.2
![Sub-menu not displaying](https://user-images.githubusercontent.com/47400982/55654716-0665ca80-57a7-11e9-84f0-030c4ac917fe.png)

**Comment by rcmp-randallw** [comment]
Here is a video of the issue:
https://1drv.ms/v/s!Au0wmqpYyP_CiYw9ggiG-4yykNUReQ

**Comment by jcarterOCV** [comment]
This will be updated in build 18.
We have moved the loading of the submenus on a per tap basis to an initial load on app open.

**Comment by rcmp-randallw** [comment]
Menu loading is drastically improved and the load popup no longer appears.
