### ISSUE TITLE
On an iPhone 5 running iOS 10.3.3 the icon to return to the main menu appears black

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#3]
On an iPhone 5 running iOS 10.3.3 the icon to return to the main menu appears black:

![image](https://user-images.githubusercontent.com/47233113/54870644-aa428580-4d66-11e9-8f02-ded7652200ca.png)

**Comment by jcarterOCV** [comment]
Will be resolved in build 16

**Comment by rcmp-randallw** [comment]
In 10.3.3 the menu (back) icon and the return (<) icon are positioned too far to the right -- should be like they appear in iOS 12.2:

Return (<)
**iOS 12.2**
![20190509_052642000_iOS](https://user-images.githubusercontent.com/47233113/57429809-7ae6bb80-71e2-11e9-996d-54a870e5219c.png)
**iOS 10.3.3**
![20190509_052637000_iOS](https://user-images.githubusercontent.com/47233113/57429810-7ae6bb80-71e2-11e9-958d-b318c13d754f.png)

Main Menu (Back)
**iOS 12.2**
![20190509_051847000_iOS](https://user-images.githubusercontent.com/47233113/57429811-7ae6bb80-71e2-11e9-93ed-5a29fbc2532e.png)
**iOS 10.3.3**
![20190509_051842000_iOS](https://user-images.githubusercontent.com/47233113/57429812-7b7f5200-71e2-11e9-861a-0d4e76f9a6d2.png)

**Comment by jcarterOCV** [comment]
We do not have control over the spacing of the icons on the navigation bar as we just set the custom image that we want to display.  The space is there as we are having to hide the standard back button and can not directly overwrite that but instead add something next to it.  
With that said, we can not change the spacing as requested.
(Note: iOS 10 accounts for <= 5% of all iOS users as noted on Apple's developer website https://developer.apple.com/support/app-store/ which these numbers were last updated from Apple on Feb 24, 2019.  With this inof, it is probably not an issue that many users will see).
