### ISSUE TITLE
Consistent menu design

### ISSUE THREAD

**Issue by ylin1CoR** [richmondrcmp/mobileapp#30]
**Is your feature request related to a problem? Please describe.**
When clicking on a menu, sometimes there's a popup and sometimes the sub-menus are displayed in a list view on screen

**Describe the solution you'd like**
Would be better if the user experience is more consistent.  Perhaps we can replace the pop-up and display them in a list view.  The user can select the sub-menu on the list view and continue to navigate down if needed (multi-level)

Eg. When clicking on Community Resources, no popup menu is displayed, but when clicking on Crime prevention, there's a popup menu.

![Popup](https://user-images.githubusercontent.com/47400982/55656532-1502b080-57ac-11e9-80a2-26962b129b3b.png)
![ListView](https://user-images.githubusercontent.com/47400982/55656533-159b4700-57ac-11e9-8de2-8e6da734d89f.png)

**Comment by rcmp-randallw** [comment]
How the content is displayed is based on the back end CMS platform and trying to reduce user  keystrokes while providing future extensible where required/desired.  

Community Resources is a Blog List where we can add additional content via the CMS at will, whereas Crime Prevention is a popup menu to link to areas under the grouping of Crime Prevention which link to a web page (to avoid first going to a Blog List to see a single item and then selecting the one item. The menu item "Crime Prevention|Auxiliary Constables" is directly tied to a single page as there is no planned need for future extensibility, whereas other items (e.g. Crime Prevention|Block Watch) is an area where there is already pages of content (i.e., Program Information and Newsletters) and so this is placed in a Blog List where we can segregate content for easier access as well add content for future extensibility and so this popup menu item links to the list and the user can select their desired sub-section content directly from the list vs. one big long serialized list of content).

Based on the varied content of the site (i.e., pages, listings, calendar items, activity map, contact list) it is not feasible nor desirable to have a single UI implementation to present content in a consistent manner -- varied content is displayed in the method best suited for the content while being able to access this varied content from a similar menu (the main menu) structure where we are limited to two pages of main menu options and at most 18 menu items).
