### ISSUE TITLE
With the banner image can we change images every 45 seconds and for the initial release can we just use one (1) image as the change is too distracting

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#33]
![20190508_064511000_iOS](https://user-images.githubusercontent.com/47233113/57355745-90e17700-7123-11e9-8c58-8e6d0c3273e4.jpg)

**Comment by rcmp-randallw** [comment]
We would like to use the following static image for the banner for the initial release:
![Parade Performers - 013](https://user-images.githubusercontent.com/47233113/57665535-0e3c3a00-75b1-11e9-9667-f49819d59eb2.jpg)

**Comment by jcarterOCV** [comment]
This will be updated in build 20

**Comment by jcarterOCV** [comment]
As well as the next version of Android we distribute

**Comment by rcmp-randallw** [comment]
@jcarterOCV As per comment from 11 days ago we would like to use the following **static** image for the banner for the initial release (for iOS and Android):
![Parade Performers - 013](https://user-images.githubusercontent.com/47233113/57665535-0e3c3a00-75b1-11e9-9667-f49819d59eb2.jpg)

Here is the link to the high res file:

https://1drv.ms/u/s!Au0wmqpYyP_CiZkMkQSNcn7mDHvUsQ

**Comment by jcarterOCV** [comment]
Sorry I forgot to change the images out while we were changing the transition time.
This should be live in the current versions of both platforms.
