### ISSUE TITLE
Commend an Officer - Drop down lists and validation

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#34]
(1) Under Commend an Officer in order to select any item from a drop down list (i.e., Date of Incident, Time of Incident, Preferred Method of Contact) you must set and then change the selected item before the control is assigned a value.

(2) Under Commend an Officer is it possible to add some validation (to avoid noise/spam) (e.g. by requiring that location, officer and/or description is more than 1 character in length)?

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
1) We do not have the ability to change the dropdown selector on any of those items.  The picker takes a "selection" which is set when the wheel is done spinning on any of those items.
2) I just added in a requirement for 1 character on all 3 of those fields.  This should be live in your current build

**Comment by rcmp-randallw** [comment]
The issue is that the selector is pre-selected to a value which isn’t set so in order to use that preselected value the user must set it to something they don’t want and then back to what they do want which is not clear nor intuitive. 

Is it possible to add a blank value to these values that if unchanged fails validation (but forces a desired selection to be set) or have the preselected values set for the field?

**Comment by rcmp-randallw** [comment]
(1) Fixed.

(2) Still Outstanding.

**Comment by rcmp-randallw** [comment]
Thanks, unfortunately this build 1.0 (25) does not progress beyond the startup page (you never get to the main menu) -- you see "Loading" appear briefly but nothing else happens.

**Comment by jcarterOCV** [comment]
@rcmp-randallw That should be resolved now.

**Comment by rcmp-randallw** [comment]
Login issue has been corrected, thanks.

**Comment by rcmp-randallw** [comment]
In iOS,
![20190914_205544000_iOS](https://user-images.githubusercontent.com/47233113/64913614-3cb15980-d6f8-11e9-8396-7628a0290feb.png)

please change the popup message to:

Missing or invalid entry on the following required field(s):

**Comment by jcarterOCV** [comment]
@rcmp-randallw iOS will be updated with the next build (26)
