### ISSUE TITLE
Accessing Developer Feedback from Settings Causes App to Crash

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#35]
If you access Settings|Developer Feedback the app crashes:

![Screenshot_20190903-205237_One UI Home](https://user-images.githubusercontent.com/47233113/64225688-4d103b80-ce91-11e9-9d23-53a1e527181b.jpg)
![Screenshot_20190903-205315_Richmond RCMP](https://user-images.githubusercontent.com/47233113/64225689-4d103b80-ce91-11e9-9979-d1d16b218673.jpg)

**Comment by jcarterOCV** [comment]
Resolved in 1.5.12 (23) version
