### ISSUE TITLE
About App Name in About this App Section

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#37]
Update the About This App section for iOS and Android:

About This App

The City of Richmond Community Safety App is a community safety policing application that helps the residents of Richmond stay connected, informed and engaged with the Richmond RCMP. This mobile application is meant to enhance the partnership between the police and the citizens of Richmond using a user friendly and engaging mobile application.

The City of Richmond Community Safety App allows the residents of the City of Richmond to play an active and vital role in helping to keep our community safe.

Access news, press releases, emergency alerts/broadcasts, a calendar of events, crime activity, crime prevention information and details on programs/services from the Richmond RCMP, all from the palm of your hand.

Help to stay connected, informed and engaged with the Richmond RCMP by downloading the City of Richmond Community Safety App today!

App Features:
- Alerts – Receive alerts and broadcasts of significant emergencies, incidents and/or road closures taking place in the City of Richmond.
- News – Read the latest information, press releases and news from the Richmond RCMP.
- Calendar of Events – View and plan for upcoming events, forums, activities and/or workshops being hosted by the Richmond RCMP.
- Crime Map – View recent and historical property crimes in and around your location.
- Report a Crime – Learn when to call the police, when to call 911, when to call the non-emergency line and file an online report for non-emergency and less serious crimes.
- Social Media – Stay connected with the Richmond RCMP’s social media channel(s).
- Crime Prevention –Learn about the Richmond RCMP’s crime prevention programs and services.
- Personal and Home Safety – Access up to date crime prevention information for personal, home, property, online presence and your business/workplace.
- Contact Us – View contact information for the emergency and non-emergency lines, the main detachment, the community police stations, media relations and other services/programs.
- Can You Identify – View the latest photos of people we are looking for help to find or identify.
- Commend an Officer – Commend an officer for service above and beyond.
- File a Complaint – File a complaint about the on-duty conduct of a member of the RCMP.
- Where Am I – Use your mobile phone to view your current location.
- Weather – View current weather conditions and temperature in your current or selected location.

iOS Version Log:
- 1.0 - Initial Version

**Comment by jcarterOCV** [comment]
@rcmp-randallw This should be live now. No update required.
