### ISSUE TITLE
Push Notifications (General and Protected) Not Working

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#38]
Sending  a protected (Auxiliaries) and General Push Notification push notification in iOS not working.  The notification appears in the Alert History and the scrolling alert footer but an push notification.

Notification settings are turned on and the protected channel subscribed and we have tried to uninstall and reinstall the latest build without making a difference.

**Comment by jcarterOCV** [comment]
Currently still working on this (build 27 does not resolve currently)
