### ISSUE TITLE
Main menu location does not update when app resumes

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#4]
I leave location A (Vancouver) with the app running and return to the phone's main menu and then arrive at location B (Richmond) and resume the app location A (Vancouver) still appears:
![image](https://user-images.githubusercontent.com/47233113/54872756-cce49680-4d86-11e9-90d3-a26bd00fb0c5.png)
 
until I press and cancel a popup menu or invoke the “Where Am I?” option (e.g. by pressing “Vancouver, BC” from the weather/location banner):
![image](https://user-images.githubusercontent.com/47233113/54872759-d3730e00-4d86-11e9-8fed-aee7647cd5a6.png)
 
and then return to the main menu:
![image](https://user-images.githubusercontent.com/47233113/54872763-e38aed80-4d86-11e9-863a-81e1b6f07b10.png)

**Note: If I resume the app and stay on the main menu the location will not update.**

**Comment by jcarterOCV** [comment]
This will be updated in build 16.
We do not do live tracking of your location while sitting on the main menu though as that would eat up the user's battery.

The current triggers to update the location/weather on the main menu is coming back to the main menu or going out of the app and coming back into it.

**Comment by rcmp-randallw** [comment]
We don't need live tracking but when someone resumes the app we would like the information updated as opposed to requiring some use action that needs to be dismissed to return to the main menu to get the updated information.  The use case is someone resuming the app, noting the weather and location and then calling the police from the Contacts section with out of date information or a member running the app to log the weather in his/her notebook at a particular time and if they don't exit and return to the main menu they information is incorrect.

What we are looking for when the app has focus (e.g. 
applicationDidBecomeActive or OnResume) to refresh the location and the temperature.  I do not think going out of the app and coming back into is triggering a refresh.

**Comment by rcmp-randallw** [comment]
In looking into this issue more there are two different behaviours on resume 1) after a long period of time when selecting the app icon the startup page is displayed and the temperature/location update; and 2)  when selecting the app icon after a short period of time from the last session where resuming the app does not display the startup page (you return to the last activity) and if that last activity happens to be the main menu the temperature and location do not update.

**Comment by jcarterOCV** [comment]
This should be resolved in build 18

**Comment by rcmp-randallw** [comment]
Using build 17 if I close the app and restart, close the app and restart while in Vancouver it is hit and miss if the app displays Richmond or Vancouver.  It seems as though if the startup is quick the location will update but if there is any sort of pause (perhaps loading the menus) the location does not update.
