### ISSUE TITLE
Invoking Search and then hitting Cancel under Calendar or Contacts causes display issue

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#40]
If you are in Calendar or Contacts and pull down to invoke Search:
![20190927_004358000_iOS](https://user-images.githubusercontent.com/47233113/65734180-aaf60480-e086-11e9-860f-9c9c254d3216.png)

and then hit 'Cancel'
![20190927_004402000_iOS](https://user-images.githubusercontent.com/47233113/65734181-ab8e9b00-e086-11e9-8801-cc8e2a3f7ff3.png)

you will see the back menu image (upper left hand corner) goes from 9 dots to 12 dots):
![20190927_004406000_iOS](https://user-images.githubusercontent.com/47233113/65734182-ab8e9b00-e086-11e9-9b44-41041abcf1fa.png)

and if you go to other sections the banner (Calendar of Events) appears behind the current banner:
![20190927_004415000_iOS](https://user-images.githubusercontent.com/47233113/65734183-ab8e9b00-e086-11e9-82d5-3dcbe75ecfc4.png)
![20190927_004426000_iOS](https://user-images.githubusercontent.com/47233113/65734184-ab8e9b00-e086-11e9-8250-9a559d72ca4d.png)
![20190927_004750000_iOS](https://user-images.githubusercontent.com/47233113/65734185-ab8e9b00-e086-11e9-9127-87d8fa721a55.png)

**Note: Did the ability to Search blog listings get removed?**

**Comment by rcmp-randallw** [comment]
Still an issue in iOS version 1.0 (29) updated on 2019-10-02.

**Comment by jcarterOCV** [comment]
Randall,

We have looked into this issue and realized that this issue is only showing on notched devices running iOS 13.0
This is an iOS bug that has been resolved in the future version of iOS (in 13.2 which is estimated to release in late October).
We saw the same issue when we tested the search bar in the "Shortcuts" app that is an Apple developed app.

With that said, I am working on an update to resolve the searchbar not showing and the color of the navigation bar when search is showing that will resolve those issues.

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
This is resolved in the updated version (1.0 build 30).

**Comment by rcmp-randallw** [comment]
Coloring has been fixed in the latest build. 

Does the search issue still require 13.2, as it is still occurring with the latest:

1. Go to Calendar and scroll down to reveal search:
![image0_1](https://user-images.githubusercontent.com/47233113/66969060-e1e38880-f03c-11e9-9628-cc99d8712468.png)
2. Tap into the search box and then hit Cancel:
![image0_2](https://user-images.githubusercontent.com/47233113/66969061-e27c1f00-f03c-11e9-9f9c-6145a99a1b50.png)
3. And then navigate and scroll down to a Blog Listing (e.g. Crime Prevention|Block Watch) and you can see the menu button in the upper left hand corner has 12 buttons instead of 9 and the banner is overlaid with 'Calendar of Events':
![image0_3](https://user-images.githubusercontent.com/47233113/66969062-e27c1f00-f03c-11e9-95b5-b191068491a3.png)

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
You are correct where this is an iOS operating system device that will be resolved in a future iOS update (this is something we found someone else running into in the same way here: https://stackoverflow.com/questions/58134631/ios-13-uibarbuttonitem-not-clickable-and-overlapping-uinavigationbars-when-using).  
Someone commented in this that the iOS 13.2 beta has resolved the issue.

**Comment by jcarterOCV** [comment]
@rcmp-randallw iOS 13.2 was released officially yesterday to the public.
We have updated a device and tested and it has resolved this issue.
