### ISSUE TITLE
Deprecated API Usage UIWebView APIs

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#41]
From Apple App Store Connect:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
This is resolved in the updated version (1.0 build 30).

**Comment by rcmp-randallw** [comment]
Not sure if this is related but in the updated version (1.0 build 30) if I go to the Calendar event (i.e., Toy Drive) and click on the email link the following appears (note the lead slashes `//`) and the message is never delivered if I hit send:

![image0_4](https://user-images.githubusercontent.com/47233113/66968982-7994a700-f03c-11e9-8a4f-c5f2dcf5b2a1.png)

**Comment by jcarterOCV** [comment]
@rcmp-randallw 
This is an issue unrelated to the UIWebview change.
I have resolved this though with build 31 that is being processed by Apple right now that you should have later today.

**Comment by rcmp-randallw** [comment]
Thanks, confirm latest version (1.0 build 31) corrects the email link issue.  

Waiting for the City of Richmond to confirm they are no longer receiving the  ITMS-90809: Deprecated API Usage error before being able to close this issue.
