### ISSUE TITLE
Copyright Notice blocked by Home Bar Indicator

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#43]
For devices without a home button the Home bar indicator encroaches on the Copyright notice of the startup screen, is it possible just for these types of devices to move the Copyright notice and City of Richmond logo upwards slightly so there is some slight separation between the Copyright notice and the Home bar indicators:

![20191021 Loading Screen](https://user-images.githubusercontent.com/47233113/67250693-42017280-f421-11e9-9ff5-54c58dc32d60.PNG)

**Comment by rcmp-randallw** [comment]
2. In iOS and Android is it possible to have the year in the Copyright notice on the startup page be dynamically built so the Year is based on the current year?

**Comment by jcarterOCV** [comment]
The home bar issue will be resolved in build 32.

In regards to the copyright year, we do not have a way to dynamically set that so each time that gets updated would have to be manually during an app update.
