### ISSUE TITLE
Commend an Officer Cancel Controls Being Cut Off

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#44]
On the Date and Time Pickers used when Commending and Officer the 'Cancel' option is being cut off:
![Screenshot_20191029-163638_Richmond RCMP](https://user-images.githubusercontent.com/47233113/67827294-ce98da00-fa8c-11e9-85e1-9ae288341dbf.jpg)
Com
![Screenshot_20191029-163655_Richmond RCMP](https://user-images.githubusercontent.com/47233113/67827346-f1c38980-fa8c-11e9-9b87-c2905c3b527b.jpg)

**Comment by cwaldonOCV** [comment]
Unfortunately I think this is an Android thing. I'm not sure if I can fix this, though I will look into it.

**Comment by cwaldonOCV** [comment]
Forgot to update you here, I overwrote the resource file it was using in order to fix this. Don't know exactly why it was having this problem, but nonetheless you shouldn't have any problems with it going forward.
