### ISSUE TITLE
Searching Calendar Items Should Search Titles, Sub-Titles and Descriptions

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#45]
In iOS searching Calendar Items is only searching Titles, it should search Titles, Sub-Titles and Descriptions:

![20191030_010511000_iOS](https://user-images.githubusercontent.com/47233113/67828043-2f291680-fa8f-11e9-897e-73662783f795.png)

**Comment by jcarterOCV** [comment]
@rcmp-randallw This will be resolved on iOS with build 32.
