### ISSUE TITLE
Filter HTML content to hyperlink addresses and contact numbers

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#6]
(1) When viewing a page can addresses be hyperlinks to Google Maps, like they are in the iPhone app (see iPhone app):
![image](https://user-images.githubusercontent.com/47233113/54873224-3bc5ed80-4d8f-11e9-92a5-fac61d6b5556.png)
**OCV: We can do this.  On iOS these default to weblinks as the operating system handles it for you.  On Android, we can tell the HTML to be a weblink and that will handle this.  We will get this updated in all of the pages.**

(2) Can telephone numbers and addresses be underlined when a hyperlink like in the iPhone app (see iPhone app):
![image](https://user-images.githubusercontent.com/47233113/54873232-7891e480-4d8f-11e9-8b6f-484102313a7f.png) 
**OCV: We can do this.  On iOS these default to weblinks as the operating system handles it for you.  On Android, we can tell the HTML to be a weblink and that will handle this.  We will get this updated in all of the pages.**

**Comment by jcarterOCV** [comment]
@rcmp-randallw Just went through and verified these.  Everything should be linking correctly.
