### ISSUE TITLE
Change size of title for Push Notification confirmation dialog

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#7]
Can the Title (e.g. Push Registration Alert) be bigger than the dialog text:

![image](https://user-images.githubusercontent.com/47233113/54873267-35844100-4d90-11e9-962e-f78499e82504.png)
![image](https://user-images.githubusercontent.com/47233113/54873271-47fe7a80-4d90-11e9-89a8-595277345e4f.png)

**Comment by jcarterOCV** [comment]
We can not edit the text size, as this is using a system dialog (kind of like the weather dialog on iOS's weather alerts).
