### ISSUE TITLE
On a Samsung SIII (Android 4.4.2) banner appears blue

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#8]
On a Samsung SIII (Android 4.4.2) the banner is still appearing blue.  Please confirm if that is the same on the oldest Android version within your top 90% -- if it is not an issue leave it, if it is please correct:

![image](https://user-images.githubusercontent.com/47233113/54873281-77ad8280-4d90-11e9-8224-ea63454b9e39.png)

**OCV: We have not been able to replicate this issue.**

**Comment by cwaldonOCV** [comment]
I believe this problem was relevant on the older version of the app and isn't present any longer. Please verify this is still a recurring issue.
