### ISSUE TITLE
On Device (Moto E (2nd Generation)) running Android 6.0 menu items are not scaling down

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#9]
On the following Device (Moto E (2nd Generation) running Android 6.0:

![image](https://user-images.githubusercontent.com/47233113/54873302-cce99400-4d90-11e9-9eba-c009ee765f5b.png)

we note the menu items are not scaling down (read too large for this display) so they break incorrectly (e.g. Information from News & Information), some items are running off the page (lower items like Crime Prevention, Personal & Home Safety and Contact Us), and the page indicator is being overwritten by Personal & Home Safety.
**OCV: This is related to the size of the available area and the minimum text size we support. I have removed the minimum size of the circle, so the text will fit as much of the area as possible on these smaller devices, but the circles could be smaller than desirable.**

**Comment by rcmp-randallw** [comment]
This is how the latest version 1.5.5 (16) is appearing (no high temperature and text is breaking mid-word) but given the form factor this is probably the best we can expect on such a small screen. 

![5151B9ED-5693-49AB-8DB0-10C21C0C0F55](https://user-images.githubusercontent.com/47233113/55029419-41a61380-4fc7-11e9-8ce6-0a6adc7aeac9.jpeg)

**Comment by cwaldonOCV** [comment]
This **should** be fixed in the next version. We don't have a device that this problem is present on, but we will try to replicate it as close as possible.
